# Blog settings
permalink: /blog/:categories/:title


# My variables
name: Daniel Macias - CTF Writeup
description: CPE 321 - Mastery Extension Writeup
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jemoji
